### ISSUE TITLE
Close window function

### ISSUE THREAD

**Issue by Piotrek605** [openskope/skope-interface#1]
I added this to render() -> return in imports/ui/pages/workspace/component.js:

```
<div className="welcome_info" display={welcomeWindowDisplay}>
            <h3>Model Run Metadata</h3>
            <button onClick={this._bound_closeWelcomeWindow}>Close</button>
</div>
```

Is there a simple way to define an onclick function that will toggle the welcomeWindowDisplay variable without editing 5 files?

**Comment by Zodiase** [comment]
If properly following redux's principles, no. The view should have as little state as possible. So clicking a button should trigger a redux action, handled by a reducer and update the global state and then update the view accordingly.

**Comment by Piotrek605** [comment]
Doesn't that mean that I need to create my own reducer? Is it not possible to handle everything in one file?

**Comment by Zodiase** [comment]
@Piotrek605 that's exactly right. The goal of the flux (or redux implementation in this case) is to create explicit actions for **everything** to eliminate tiny groups of states within the UI.

In practice, if we are dealing with something like a widget, meaning its internal states will **never** impact the outside, it may have its own states. But it's never that easy, there's more to do.

Take the example of  an `input` tag. In React it could be configured in two entirely different modes and can **not** switch modes after initialization. In one mode, where `value` is provided as a prop, it enters "stateless" mode and requires a `onChange` handler. In the other, where `value` must **not** be provided, it enters "state-full" mode and manages its own value. The second mode, often much easier (to use) than the first mode, however, introduces these issues:

- You **never** know its accurate state at any time.
- You **have to** properly given it initial values and reset it whenever needed.

And React (or any templating engine I believe) won't be able to help you at all. Basically you need to manually change the state of the element, which is a big no no if you want everything to be manageable.

**Comment by Zodiase** [comment]
You probably could design a smart binding mechanism that doesn't violate flux principles to help you write less code, but ultimately explicit actions and reducers are needed, one way or another.

**Comment by Piotrek605** [comment]
```
/**
 * This reducer is used to toggle the visibility of a layer in workspace.
 */

export const WORKSPACE_TOGGLE_LAYER_VISIBILITY = (state, action) => {
  const {
    index,
    visible,
  } = action;

  const visibilityGiven = !(typeof visible === 'undefined');

  return {
    ...state,

    workspace: {
      ...state.workspace,

      layers: state.workspace.layers.map((layer, layerIndex) => {
        if (layerIndex === index) {
          // Toggle the visibility of the layer.
          return {
            ...layer,

            invisible: visibilityGiven ? (!visible) : (!layer.invisible),
          };
        } else {
          return layer;
        }
      }),
    },
  };
};
```

I followed your code for changing the visibility of a layer and I wrote this reducer:

```
export const WORKSPACE_CLOSE_WELCOME_WINDOW = (state, action) => {
  const {
    value,
  } = action;
    
  return {
    ...state,

    workspace: {
      ...state.workspace,

      welcomeWindowClosed: value,
    },
  };
};
```

At some point I had the new value of my 'welcomeWindowClosed' variable appear in the address bar on the press of the button but it would only change once and the new value wouldn't come back to the HTML code to reflect the change in the website's text. What might I be doing wrong?

**Comment by Piotrek605** [comment]
To put it in the wider context, here is my HTML code:

```
        <div className="welcome_frame" style={welcomeWindowClosed ? welcomeWindowStyle.hidden : welcomeWindowStyle.visible}>
            <div className="welcome_background">
            </div>
        
            <div className="welcome_info">
                <h3>Model Run Metadata</h3>
                <button onClick={this._bound_closeWelcomeWindow}>Close</button>
                <p>This is the metadata of the layers.</p>
                <p>{welcomeWindowClosed ? "true" : "false"}</p>
            </div>
        </div>
```

The function in component.js:

```
  _closeWelcomeWindow(event) {
      const {
          closeWelcomeWindow,
          welcomeWindowClosed,
      } = this.props;
      
      closeWelcomeWindow(!welcomeWindowClosed);
  }
```

The snippet I added to container.js:

```
    welcomeWindowClosed,
    closeWelcomeWindow: (welcomeWindowClosed) => {
        store.dispatch({
          type: actions.WORKSPACE_CLOSE_WELCOME_WINDOW.type,
          value: welcomeWindowClosed,
        });
    },
```

**Comment by Piotrek605** [comment]
I actually just had a small bug in the code, it's working now, thanks!
