### ISSUE TITLE
Revise what data to be displayed in search result cards

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#104]
We want to display more structured data in the search result cards (cards for short below). We should decide on the details and finalize the design in this issue.

**Comment by jterstriep** [comment]
- [ ] Add "type" field to filters immediately after the search field
- [ ] Change Point of Interest to "Geographic Area"
- [ ] Add tooltip to Geographic Area "Click the map to find datasets that overlap that point."

**Comment by Zodiase** [comment]
Closing this as it's better covered by other (open) issues.
