### ISSUE TITLE
Connect analytics tab with data service.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#114]

**Comment by jterstriep** [comment]
Timeseries service will generate 3 timeseries with absolute values (vs offset or percentage) to represent uncertainty.

The CSV will be generated by the timeseries service based on a format parameter.

**Comment by Zodiase** [comment]
![mar-09-2018 18-52-11](https://user-images.githubusercontent.com/1815174/37236207-080007b8-23cb-11e8-866f-a2538c36869f.gif)
