### ISSUE TITLE
Explore page cleanup for 3/16

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#123]
Explore Page
- [ ] Add filter directly below search field for 'Type' based on metadata type
- [x] Variables Filter should filter on variables.class rather than variables.name
- [x] Change "Point of interest" to "Geographic Area"
- [x] Add subtitle under Geographic Area called "Click to filter datasets overlapping your area of interest."
- [x] Change "Timespan" to "Time Period"
- [x] Card subtitle should be region.name and timespan.name

**Comment by Zodiase** [comment]
What field to use for the `"Type"`?

**Comment by jterstriep** [comment]
Let's leave the "Type" field alone for now. We'll come back to it when we start running models.
