### ISSUE TITLE
Temporal control components

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#130]
A standard temporal control component is needed with the following features
- starting value and ending value of dataset (fixed)
- user selected starting and ending value (data entry)
- current value
- step up/down buttons
- play/pause (auto increment) button

The value can be assumed to be an int and represent a year. This could change to be a date field in the future but use int for now.

The timeline with handles would be nice but not required. If the timeline is provided it should have handles that interact with the user select starting end ending data entry fields.

This component should be visible and used on the mapview, graphview, and download tabs. 

This component could be adapted for use on the discover tab. Where pre-determined starting and ending dates for the SKOPE collection would be used and the animation controls could be hidden.

**Comment by Zodiase** [comment]
![image](https://user-images.githubusercontent.com/1815174/38044098-6d66b8a6-327e-11e8-997c-9d0237a54a8e.png)

**Comment by Zodiase** [comment]
![image](https://user-images.githubusercontent.com/1815174/38060902-61dd2d4c-32b2-11e8-8ddf-47213be3908e.png)

Temporal controls implemented in 41e941b1352fe7fbdc1cfd93b78a1a355abe76a1. It’s still only controlling the state within the Overlays Tab.
