### ISSUE TITLE
There needs to be a color ramp and legend shown on or just off the map.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#135]

**Comment by jterstriep** [comment]
Geoserver should be able to generate the legend. I'll have to experiment to get the specific request.

We'll need to determine the exact design and where it will be located. It seems like it should be near the variable name, on the map, or just below the map.

**Comment by Zodiase** [comment]
From my understanding of the purpose of the legend, it'd be better to be somewhere in the map so it's easier to compare the color ramp. 

We also need to add a scale (also part of the feedback) at some point. I think they can stay fairly close together and look something like what Google Map has.

![screen shot 2018-03-27 at 5 39 33 pm](https://user-images.githubusercontent.com/1815174/37998831-dd0ef342-31e5-11e8-9d38-33e86a35bf9d.png)

**Comment by Zodiase** [comment]
Openlayers dynamic scale line example:
https://openlayers.org/en/latest/examples/scale-line.html

**Comment by Zodiase** [comment]
Pixel-wise operation for re-coloring.
https://openlayers.org/en/latest/examples/raster.html

**Comment by Zodiase** [comment]
Added a static legend (hard-coded) as an overlay on the map: 
![image](https://user-images.githubusercontent.com/1815174/39891091-5539c268-5462-11e8-8fc9-1cc1dd8b8b1c.png)

@jterstriep Does the legend change over different bands?

**Comment by Zodiase** [comment]
A temporary solution implemented on dev branch https://github.com/openskope/skope-interface/tree/add-overlay-legend. Its image is available to be pulled as `openskope/webapp:add-overlay-legend`.

This solution only works for wms overlays as it assumes the format of a wms url and extracts the layer name from it. It then builds the legend url from the layer name.

**Comment by Zodiase** [comment]
@jterstriep 
The implementation is not merged to master since it heavily relies on the wms url structure. Do you want to put the legend url in the ES documents, or just ship this?
