### ISSUE TITLE
Add tab bar across the site

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#136]
The blue tab bar should be shown on every page. It should have the following items; Discover, Info, Map View, Graph View, Download, Model. From the "Discover" view the remaining options are greyed out. 

When returning to the Discover view it should be in as a consistent state (i.e. previously selected filters, etc) as possible. If the Discover button operated identically to the Explore Data option of the hamburger menu that would be OK for the SAA meeting but will need improvement long-term.

**Comment by Zodiase** [comment]
Resolved with 852338d93b0d0a298cfd90bd206566d4156e180e and 9ab42cc78dec28a79260f00dffb626a5f183dcf0.
