### ISSUE TITLE
Define geographic area by drawing on map

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#137]
The ability of the user to define an area of interest by drawing on the map is a key feature. The resulting boundary should be persistent across tabs and viewed in the control map (left panel map).

- [x] draw rectangle or polygon
- [x] clear aoi once defined
- [x] show aoi boundary on control map
- [x] pass boundary to graph service

**Comment by Zodiase** [comment]
Openlayer examples:

https://openlayers.org/en/latest/examples/draw-shapes.html
https://openlayers.org/en/latest/examples/draw-freehand.html
https://openlayers.org/en/latest/examples/draw-features.html
https://openlayers.org/en/latest/examples/modify-test.html
https://openlayers.org/en/latest/examples/modify-features.html

This example seems to be loading and saving vector features from and to ArcGIS: https://openlayers.org/en/latest/examples/vector-esri-edit.html

**Comment by Zodiase** [comment]
Still working on the continuity. Other features are covered by c93be01d3a9a0d4b3af122f91feae7647f37ce65.

**Comment by Zodiase** [comment]
Resolved by 72803d8bd871d067c3938c3806df2cf886af05ce
