### ISSUE TITLE
Boundary overlay should not have any fill. (Now it has a very light white shade.)

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#145]
### Notes:

- Openlayers doesn't support styles defined within the GeoJSON document.
- Need to implement a way to specify styles for vector layers, or
- try `ol.layer.Vector.setStyle()` after the layer is rendered.

### Links:

- http://openlayers.org/en/latest/apidoc/ol.layer.Vector.html#setStyle
- http://openlayers.org/en/latest/apidoc/ol.html#.StyleFunction
- http://openlayers.org/en/latest/apidoc/ol.style.html

**Comment by jterstriep** [comment]
I believe this is resolved. If so, @Zodiase please close.

**Comment by Zodiase** [comment]
@jterstriep This is not yet resolved. I have implemented this in the underlying map library and tested with an independent demo but the latest version of that library has not been incorporated in this project.
