### ISSUE TITLE
Add map scale to the Map View

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#147]
A scale value should be overlayed on the large map view map. 

* The scale should probably be in either meters or degrees. Let's assume meters for now. 
* The scale could be produced by openlayers or geoserver. Let's see if the openlayers solution works and we'll use geoserver produced scale as a fallback.

**Comment by Zodiase** [comment]
Openlayers has a built in ScaleLine control available.

Demo: http://openlayers.org/en/latest/examples/scale-line.html

**Comment by Zodiase** [comment]
Add by 0b69174b0e2804a6c048f72d19863cd4eea645a1.

**Comment by tmcphillips** [comment]
The scale does not appear on the any of the maps, including the large map in Map View.  It needs to go in the bottom left corner of every map.

**Comment by Zodiase** [comment]
@tmcphillips The scale was removed because it does not work with the current display project and we haven't found a workaround. 

Also for the record the scale should be at the bottom-right corner, as far as I know.

**Comment by Zodiase** [comment]
Please follow #182.

**Comment by abrin** [comment]
seems premature to close if the users need it.  I get that we don't have
a solution currently, but that suggests a reprioritization, not closing
the ticket.

On Wed, Jun 27, 2018, at 8:06 AM, Xingchen Hong wrote:
> Closed #147[1].


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].

Links:

  1. https://github.com/openskope/skope-interface/issues/147
  2. https://github.com/openskope/skope-interface/issues/147#event-1704146855

**Comment by Zodiase** [comment]
@abrin Because there is already another issue open and has more context about the problem.
