### ISSUE TITLE
Add a “Working” or Rotating circle or whatever while graph is generating 

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#152]

**Comment by Zodiase** [comment]
There is already a animating progress bar when the graph data is being loaded. The animation, however, will not play (same for everything else on the page) while the graph is being generated since the main thread of the browser is being occupied. I don't think this is fixable.

**Comment by abrin** [comment]
at least add a please wait

**Comment by kintigh** [comment]
From my standpoint the current state is OK.
