### ISSUE TITLE
Gracefully handle long processing time associated with some graph generation.

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#154]
Keith's document suggests that we figure out how to decide if too big an area is selected and display “Select a point or smaller area”. Alternatively, we could have some sort of timeout associated with graph request.

**Comment by Zodiase** [comment]
The timeout must be handled on the server otherwise the client can easily DDoS the server. I'd expect the server to return some sort of [400 Bad Request](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) error stating "the request is too large".

**Comment by tmcphillips** [comment]
Do you want to be able to specify a timeout in the timeseries request? There will be a configurable default timeout period on the server.

**Comment by Zodiase** [comment]
Client side needs to recognize the error code / message and display a specific error (ask the user to select a smaller area?)

**Comment by tmcphillips** [comment]
The 400 Bad Request response returned by the service when the processing time for a request is excessive has an error message starting with "External process exceeded time limit".  See [timeseries.timeout.tests.js](https://github.com/openskope/timeseries-service/blob/85be03fd4e316dc42d8257434cd51634159e862a/src/__tests__/timeseries.timeout.tests.js).  This version of the timeseries service is now running on the staging server.

The default timeout (currently 5000 ms) is configured via an environment variable (TIMESERIES_MAX_PROCESSING_TIME) in the Dockerfile and can be overridden by docker-compose.  A 'timeout' value can be specified in the request (primarily for testing purposes) but is ignored if it exceeds the timeout value given by the server configuration.
