### ISSUE TITLE
Provide mechanism to provide feedback on SKOPE

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#174]
Keith suggested that he could accept emails.

**Comment by Zodiase** [comment]
Did Keith mean a `<a href="mailto:somebody@company.com">`?

**Comment by Zodiase** [comment]
This change requires the app settings file to be updated to add the new config property `public.contactEmail` as seen here: https://github.com/openskope/skope-interface/blob/d720fecfd8e8a31d872604e5525b8e1d3cf238c4/meteor-app.settings.default.json#L3

**Comment by Zodiase** [comment]
@jterstriep Please see the config change in the above comment.
