### ISSUE TITLE
Incorrect button coloring on map selection tools.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#190]
From @kintigh: On Map selection the Hand and Draw a rectangle selection are colored exactly opposite of what I would expect.  It seems to me the active one should be the white, that is highlighted, one and the gray ones not selected.

**Comment by Zodiase** [comment]
![image](https://user-images.githubusercontent.com/1815174/40016677-b52cacae-577c-11e8-8162-bb074caef119.png)

@kintigh These buttons are a group of toggle buttons, where the active one among the group should look like it's been pressed down. Here are a few examples:

From Microsoft Word:
![image](https://user-images.githubusercontent.com/1815174/40016824-3befdd74-577d-11e8-8258-ba92eefb40f1.png)

From Google Docs:
![image](https://user-images.githubusercontent.com/1815174/40016958-95fb0c76-577d-11e8-9d06-c0dfb100857b.png)

From [Material Design](https://material.io/design/components/buttons.html#anatomy):
![image](https://user-images.githubusercontent.com/1815174/40016854-48913e74-577d-11e8-9ff1-d00aeebd8b57.png)

From [Bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons):
![image](https://user-images.githubusercontent.com/1815174/40016869-53067842-577d-11e8-9e6a-03db2e52bd21.png)

The library I'm using doesn't provide an out-of-box solution for this type of buttons so I improvised a bit to make the active one have a darker background. I can try to make it more obvious it's "pressed down".

**Comment by kintigh** [comment]
Yes I think having it something other than the background color would do it.  Thanks.
Keith

**Comment by Zodiase** [comment]
Now the selected has a stronger border in addition to a darker background. The non-selected ones have a weaker color for the icon. The shadows are removed all-together to avoid being mis-interpreted as an indication of selection.

![image](https://user-images.githubusercontent.com/1815174/40089838-9f244bcc-5873-11e8-9954-f05d82e5196d.png)
