### ISSUE TITLE
restrict zoom (for example when a point is selected)

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#192]

**Comment by kintigh** [comment]
If a point or very small area is selected in graph view, moving to map view is so zoomed in that you get "map not available."  I thought we were going to limit the zoom somehow.

**Comment by Zodiase** [comment]
This has been resolved by 0544a02462c0b56783dc7f54e7e2fbdac55e769b which is released in `0.1.20`.

**Comment by Zodiase** [comment]
Max zoom level is set to 18 which should not show `map not available` any more.
