### ISSUE TITLE
Focus boundary should be outlined on the big map in map view.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#198]
From @kintigh:

> In the map view, the area outlined on the left should also be outlined on the right, as that is the study area and the area that will be averaged in the graph view.  WIthout this change, I think we convey the wrong idea about what is represented in the graph view.

**Comment by Zodiase** [comment]
IMO this now has to be resolved since #197 just broke the connection between the big map in map view and the small map in the side panel. Without this #197 would make the big map much more meaningless.

**Comment by kintigh** [comment]
If this needs to be resolved, why did it get closed?

**Comment by Zodiase** [comment]
@kintigh Because it's resolved by commit 45523c5.

**Comment by kintigh** [comment]
OK.  DO you have any idea when the commit will affect the staging server.  It is not showing now.

**Comment by Zodiase** [comment]
Changes should be reflected in version `0.1.20`.
