### ISSUE TITLE
Display the Lat. and Long. corresponding to point under cursor on any map.

### ISSUE THREAD

**Issue by tmcphillips** [openskope/skope-interface#207]
Currently it is difficult to know what (or where) you are looking at on the maps in the web app if you zoom in at all. The coordinates corresponding to the point under the mouse cursor should be displayed somewhere near the map and updated in real time as the cursor is moved. All maps that can be panned or zoomed should have this same behavior.

**Comment by Zodiase** [comment]
Implemented in dfe00e0f1e32e87e7372c9114c44229289a9c726 and should be deployed in version `0.1.23`.

**Comment by Zodiase** [comment]
Reopen for verification

**Comment by tmcphillips** [comment]
The lat and long values are obscured by the color ramp legend on the main map in Map View for the LBDA dataset.

**Comment by kintigh** [comment]
SKOPE is now displaying the proper values, in map view the values are obscured by the legend.

**Comment by Zodiase** [comment]
The fix for the collision issue will be deployed with version `0.1.25`.
