### ISSUE TITLE
Split workspace page into smaller components

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#4]
Post below if you have any questions.

**Comment by Piotrek605** [comment]
https://github.com/openskope/skope-interface/blob/workspace/meteor-app/imports/ui/pages/workspace/charts/container.js#L36

"Uncaught TypeError: Cannot read property 'getState' of undefined"

What did I do wrong?

**Comment by Zodiase** [comment]
Did you pass the store to all of your components?

**Comment by Piotrek605** [comment]
https://github.com/openskope/skope-interface/blob/workspace/meteor-app/imports/ui/pages/workspace/component.js#L325

**Comment by Zodiase** [comment]
But that `store` is `undefined`.

**Comment by Piotrek605** [comment]
Done on workspace/251111db106ff09afd4c54f70040a9300f80fab9.

**Comment by Zodiase** [comment]
Resolved.
