### ISSUE TITLE
User should be able to sort search results in different ways.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#40]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

**Comment by rushgeo** [comment]
Some of the sort possibilities include Creation Date, Result Type, Creator, and Status.

Perhaps there could be a bar above or below the filter bar that works similarly. It would always appear, and show the default sort. Users could change it, or add additional sorts (e.g. sort first by type, then by date descending).

**Comment by Zodiase** [comment]
Removing the User Story tag for implementation.

The goal would be adding a rough placeholder for all the potential search options and only have a few trivial ones there for now.
