### ISSUE TITLE
When needed, user could expand the search result items to reveal more details, without leaving the page.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#42]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

**Comment by rushgeo** [comment]
The user could click on More Information, and then the result box could either expand down, or a popup could appear with the rest of the result's metadata. 

To do this, it would be helpful to have an idea of what the complete metadata for an item may look like. We can always add to the list of returned data, but we should plan for the approximate space the full metadata display would take up in the expanded search result (including preview images, sections that may apply to some result types but not others, etc.). In either case, we may need a vertical scroll bar or tabs to organize content that may not fit in a single view.

**Comment by abrin** [comment]
If the application is fast enough, and the basic metadata is provided, is this necessary?  I think more definition for this user story is needed prior to fleshing out.

**Comment by Zodiase** [comment]
Design for now:

Clicking on each icons in one result will bring up the dialog modal in the second screenshot with more details.

![image](https://user-images.githubusercontent.com/1815174/35717737-b7972b52-07a6-11e8-9f2e-dbcfa0f147fe.png)

![image](https://user-images.githubusercontent.com/1815174/35718639-0cae6a52-07ab-11e8-884c-9be435b4a515.png)
