### ISSUE TITLE
User should be able to filter the search results with some spatial constraints.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#43]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

Note:
For example, for a specific bounding box, find all search results that collide with it or are contained within it.

**Comment by rushgeo** [comment]
I like the way the spatial filtering works in TopoLens. In the mockup made, I envisioned something like that in a popup, and then the list of filters would indicate that a spatial filter is enabled.

Perhaps in the list of filters, it could show the name of the region if it was selected from a list (e.g. a state name) or from an uploaded file name, or show "custom" if it was hand-drawn.

TopoLens example:
![topolens_boundary_management](https://user-images.githubusercontent.com/10775395/29878462-932183e0-8d70-11e7-9708-a09042756c2b.jpeg)

**Comment by abrin** [comment]
I think having a single way of interacting would work best, perhaps just  a single bounding box, so they can choose the arbitrary locations?  While I like Johnathan's mockup, it seems like a lot of work, and more than necessary to get people where we want to go initially, though longer-term, it might be nice.

**Comment by Zodiase** [comment]
A rough spatial filter component has been added to the search page, though the functionality is very limited. Currently the user can click on it to select a point to see only the search results that cover this point.

If more functionalities are needed, please give concrete examples on how the user would take advantage of each of them.
