### ISSUE TITLE
Workspace needs a toolbar for common controls.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#45]
Things could go into the toolbar:
- Help
- Info
- Metadata
- Contextual controls

**Comment by jterstriep** [comment]
The toolbar should be as consistent as possible across the site in both location and presentation. In most cases, the direct links, collectively known as actions, to the necessary information are provided within the metadata of the page context. This currently includes info, metadata, and download fields.

**Comment by Zodiase** [comment]
@jterstriep What will toolbars on other pages look like to you?

**Comment by Piotrek605** [comment]
What exactly do you mean by metadata and contextual controls? The metadata will be displayed on the modal that appears when you click the info button.

**Comment by Zodiase** [comment]
Closing this as a naive toolbar has been added by #61. Will open a new one with detailed design and improvements.
