### ISSUE TITLE
Everything needs a help button

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#46]
- Search page (may need multiple ones)
- Any modal
- Workspace
- Model page
- etc...

**Comment by jterstriep** [comment]
Page level help buttons should be displayed on any page to describe basic and advanced features. Help buttons should be consistently styled and displayed across the site.

**Comment by Zodiase** [comment]
@CiciMa please provide design here when ready.

**Comment by CiciMa** [comment]
Workspace Prototype
toolbar & help button design
https://framer.cloud/UQdIH

**Comment by Zodiase** [comment]
Closing this since the requirement is too general and the current UI is still changing a lot.
Also there's currently a global help button placed in an odd location in the layout, which could be used as a fall back if we can't find better spots for more granular contextual helps.
