### ISSUE TITLE
Put the info button in the toolbar.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#47]

**Comment by Zodiase** [comment]
This depend on #45.

**Comment by Zodiase** [comment]
@Piotrek605 do you have a PR for this? How is this completed?

**Comment by Piotrek605** [comment]
I thought marking it as complete instead of closing it was a good way to indicate that it's been implemented in a branch but in this case I'm putting it back to in progress.

**Comment by Zodiase** [comment]
Well when it's done, you should be able to create a PR for it.

**Comment by Zodiase** [comment]
Resolved by #61.
