### ISSUE TITLE
In Workspace, User would like to see the metadata of the result.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#52]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

**Comment by jterstriep** [comment]
The users should be able to review metadata concerning the either data sources or model results. Metadata review should be consistently available across the site using a common icon. On the Search Page, the metadata should be available from the results tile. On the Workspace, the metadata should be available at either the workspace or layer level.

**Comment by jterstriep** [comment]
Issue moved to [openskope/SKOPE #3](https://github.com/openskope/SKOPE/issues/3) via [**ZenHub**](https://www.zenhub.com/)
