### ISSUE TITLE
User would like to define an area of interest in Workspace for quick view switching.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#53]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

Note:
For example, User would like to quickly switch from landmark A to landmark B.

**Comment by jterstriep** [comment]
"Areas of Interest" is nickname for a set of features that allow users to define and reuse specific spatial areas of particular interest. On the Workspace, the AoI can be used to center and zoom the map display. On the Search Page, an AoI can be used to filter models results to ones that overlap with the AoI. On the Model Page, the AoI defines the extent of the modeling area.

When presented on a page that includes a map, the current AoI should be rendered as a boundary.

The system should maintain a set of pre-defined AoIs that are available to all users.

Users should be able to create, name, select, and delete their personal AoIs.

**Comment by rushgeo** [comment]
Jeff's description sounds good. The functionality could be similar to the boundary selection/uploader in TopoLens. 

I would like the ability for all of my user-created AOIs to be accessible on any workspace. E.g. I could define a site of interest, and be able to zoom to it quickly no matter which set of results I happen to be looking at.

**Comment by jterstriep** [comment]
Issue moved to [openskope/SKOPE #4](https://github.com/openskope/SKOPE/issues/4) via [**ZenHub**](https://www.zenhub.com/)
