### ISSUE TITLE
User would like to compare the results of two runs.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#54]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

**Comment by jterstriep** [comment]
Issue moved to [openskope/SKOPE #2](https://github.com/openskope/SKOPE/issues/2) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rushgeo** [comment]
I think the comparison happens between two layers in the workspace. That suggests:

1. We need a good method of getting new layers into the workspace (a good search popup, or a way to return to the workspace after doing a search if that's a separate page)
2. A way of starting the comparison
3. A way of selecting the layers to compare  
  
For starting the comparison, perhaps clicking on one of the layers in the table of contents could provide "Compare" as an option.  
For selecting layers to compare, perhaps the UI could suggest layers based on the first selected layer. That could be layers of the same data type, e.g. both temperature layers.

**Comment by rushgeo** [comment]
Oops, this was moved to another repo. Closing.
