### ISSUE TITLE
User would like to read and post comments about the model run.

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#55]
This is a **`User Story`**. It needs to be expanded with context and detail. Create separate PRs for feature implementations that support this User Story. The goal here is to develop and finalize the story of how the user would accomplish the task.

Note:
Use the existing commenting system on Clowder.

**Comment by jterstriep** [comment]
Issue moved to [openskope/SKOPE #1](https://github.com/openskope/SKOPE/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jterstriep** [comment]
Moved to SKOPE.
