### ISSUE TITLE
Populate the Search Page Filtering Panel

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#57]
The filtering panel should have the following elements:
- model name (title: Model) 
- creator (title: Creator)
- status (title: Status)
- rank (title: Range, range=1-5)
- input types (title: Inputs)
- result types (title: Results)

Note: this issue has been edited to remove date fields. Date field filter will be handled at a later stage.

**Comment by CiciMa** [comment]
Finished revised 
Branch: search-page
Commit: d2fbda6

**Comment by Zodiase** [comment]
Please create a PR if this is completed.

**Comment by CiciMa** [comment]
What is PR?

**Comment by Zodiase** [comment]
@CiciMa A Pull Request is a dedicated issue thread for merging your branch to a target branch, typically the master branch. Creating it tells people you have something ready to be merged, while the PR itself can check for conflicts and highlights the total changes and commits.

**Comment by Zodiase** [comment]
Since the only referenced PR is closed, this is still not done yet?
