### ISSUE TITLE
Compose result tiles

### ISSUE THREAD

**Issue by jterstriep** [openskope/skope-interface#58]
Result tiles should have the following content:
- title (1)
- model type
- creation date (yyyy-mm-dd)
- thumbnail
- creator
- ranking
- status
- period (2,4)
- input types (3,4)
- result types (3,4)

(1) Title should be a link as provided by the view data field 
(2) Period is a new metadata field that describes the starting and ending date of the model in human readable format. 
(3) Input type and result types are a list of nicknames that describe the types of data used as inputs and outputs of the model. This information is of lesser importance perhaps indicated by a smaller font.
(4) In the case of non-modeled data (i.e. model type == Data), period,  input types, and result types may be empty strings in which case they should not be displayed.

In addition to the metadata displayed within a tile, a series of quick actions should be available along the bottom of the tile. Each quick action is represented by a link within the metadata. If a metadata field is empty the quick link should not be displayed.

Quick actions include -
- View - navigate to workspace page (use title as anchor)
- Info - navigate to information page on site
- Reference - navigate to external site
- Download - download data to host
- Create From - navigate to model form

**Comment by Zodiase** [comment]
Closing as this is no longer up-to-date.
