### ISSUE TITLE
Search Kit Exploration

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#6]
Let's put down relevant resources, questions, discoveries and notes in this thread.

**Comment by CiciMa** [comment]
Result-item-timeline
<img width="456" alt="screen shot 2017-07-24 at 4 38 18 pm" src="https://user-images.githubusercontent.com/20867069/28545970-aa2851ee-708e-11e7-83a4-18dcf7e38d34.png">

The layout for searchresult with a timeline range that specify users to choose

**Comment by CiciMa** [comment]
The documentation of overriding component in SearchKit http://docs.searchkit.co/stable/setup/extending-components.html

Source document --> Facet Filter Component
https://github.com/searchkit/searchkit/blob/develop/src/components/search/filters/facet-filter/FacetFilter.tsx
