### ISSUE TITLE
Model Page

### ISSUE THREAD

**Issue by CiciMa** [openskope/skope-interface#65]
TODO List:

- Navbar name correction from "Model" to "PaleoCAR"
- Prediction Years (400,100- 300)
Add Components:
- Scenario Name
- Description 
- Map
- Submit button 

Remove Components:
- Latitude
- Longitude

Layout Design:
- Consistency with Workspace Page

**Comment by Zodiase** [comment]
@jterstriep I can see most of these changes in master, with the exception of "Prediction years" not following what's stated in the description. Does anything still need to be changed?

**Comment by Zodiase** [comment]
Closing as this is out-of-date.
