### ISSUE TITLE
Model button on homepage should be removed

### ISSUE THREAD

**Issue by rushgeo** [openskope/skope-interface#67]
Right now, there's a Model button that leads to a form that collects the parameters for a PaleoCAR run. The original idea of this box on the front page with text "Contribute your paleoenvironmental model!" was to link to information on contributing an entirely new model to SKOPE. We haven't decided what that information will look like yet, but will probably be an page of text at first.

If we remove this button, there may be no other way to navigate to the PaleoCAR run configuration right now, but that's a separate issue.

**Comment by jterstriep** [comment]
I've got a new menu bar planned that will complete navigation without going
to the home page. I haven't created an issue yet but that's a top priority.

**Comment by jterstriep** [comment]
This was done temporarily to provide a direct link to the model generation page. 

We are working on a new header bar that will provide the link for the PaleoCAR modeling page. And we can correct this link. But this leads to additional questions regarding the front page, see issue https://github.com/openskope/SKOPE/issues/5.

**Comment by Zodiase** [comment]
This should have been resolved.
