### ISSUE TITLE
SearchKit overriding component

### ISSUE THREAD

**Issue by CiciMa** [openskope/skope-interface#8]
- The documentation of overriding component in SearchKit http://docs.searchkit.co/stable/setup/extending-components.html

- Source document --> Facet Filter **Component** 
https://github.com/searchkit/searchkit/blob/develop/src/components/search/filters/facet-filter/FacetFilter.tsx

**Comment by Zodiase** [comment]
@CiciMa please be aware that #6 has already been opened for search kit related notes. **Always check existing issues (even closed ones) before opening new ones.**
