### ISSUE TITLE
What docker image should local/elasticsearch/docker-run.sh start?

### ISSUE THREAD

**Issue by tmcphillips** [openskope/skope-interface#80]
I'm setting up to run the skope web app on my various development machines.  When I try to start elasticsearch using the command 'npm start' in the local/elasticsearch directory I get this output:

```
$ npm start

> skope-dev-elasticsearch@1.0.0 start /mnt/c/Users/tmcphill/GitRepos/skope-interface/local/elasticsearch
> bash docker-run.sh

Unable to find image 'elasticsearch:2' locally
```
There is a commented line in the docker-run.sh script that indicates that the image might be
docker.elastic.co/elasticsearch/elasticsearch:5.5.0, and indeed the command below does download and run a docker container running elasticsearch:

    docker run docker.elastic.co/elasticsearch/elasticsearch:5.5.0

Is this the correct version to use, and do we want to host our own image at Docker Hub?

**Comment by tmcphillips** [comment]
It looks like the problem accessing elasticsearch:2 is an authentication issue when connecting to Docker Hub.  It works fine from a different docker installation (running on MacOS).

**Comment by tmcphillips** [comment]
And I now can run elasticsearch:2.

**Comment by Zodiase** [comment]
Yup it should run the latest version under `2.*`, since that's what Clowder uses. I have no idea why docker would not be able to find it. There isn't any issue with the launch script.
