### ISSUE TITLE
When `extent` is provided on MapView, it can only zoom out but not zoom in

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#92]

**Comment by jterstriep** [comment]
That's interesting. Is this an OpenLayers issues?

**Comment by Zodiase** [comment]
No it's probably a bug in the wrapper I wrote for OpenLayers.

**Comment by Zodiase** [comment]
The bug was caused by unwanted feedback when flushing the property values to their corresponding attributes. Now the flushing function will suppress reactions to the attribute being flushed.

Detailed **incorrect** flow:

- Zoom with controls on the map.
- Openlayers is trying to change the zoom, triggers `change:resolution`.
- View change handler then tries to flush the current `extent` property (which is given by the map) to attribute. This triggers an attribute change event of `extent` attribute.
- Attribute change handler then converts the new `extent` attribute value to a property value then sets the `extent` property.
- Extent setter then updates the map view, which triggers `change:resolution` again.
- ... (at this point there is already an unnecessary loop)
