### ISSUE TITLE
Workspace layers should be able to play animation

### ISSUE THREAD

**Issue by Zodiase** [openskope/skope-interface#94]
So far the "play" button doesn't work. Now the layers are loaded and the year switching is stable, the next step is to have the "play" button automatically advance the year.

@tmcphillips Is there an expectation on what pace the animation should be playing at?

Maintaining a fixed playback speed may not be feasible due to network performance issues. A more reliable approach is to use a slide-show style, where a fixed amount of delay is maintained before loading the next frame, but the time spent on loading the frame is not counted towards the delay.

- [ ] ~UI should have clear indicators of the frames being loaded.~
- [ ] ~The year stepping buttons and input fields should be disabled while the animation is in progress to avoid race conditions.~
- [ ] ~UI should have indicators of how much time is remaining until the advancement to the next frame.~
- [ ] ~Pre-fetch the next frame to smooth the animation.~
- [x] When at the end of the temporal range, clicking the "play" button restarts the animation from the beginning of the temporal range.
    - Otherwise "resumes" the animation from the current time frame.

**Comment by tmcphillips** [comment]
These are good requirements for the animation.  However, my understanding is that the animation is not a high priority feature for users.  It's also not a feature we are targeting for the 0.1 release.  Unless we hear otherwise from the rest of the team, let's hold off on this until 0.1 is up and running and we have made a comprehensive plan for the 0.2 release.

**Comment by Zodiase** [comment]
@tmcphillips Sure. I'm not adding this to the Release 0.1 project.

**Comment by Zodiase** [comment]
Basic functionality is implemented in 8438d28cb57e94d46f738bfd4340cd92d5432f79. Advanced features are discarded until requested.

**Comment by Zodiase** [comment]
![image](https://user-images.githubusercontent.com/1815174/38004731-3af47d48-3203-11e8-9935-e15811100825.png)

Frames are being played at `1`-second intervals. However the layers are not being loaded currently so I don't have any visual confirmation if the animation is working.
